CREATE CATALOG IF NOT EXISTS lab5;
CREATE SCHEMA IF NOT EXISTS lab5.bronze;
CREATE SCHEMA IF NOT EXISTS lab5.silver;
CREATE VOLUME IF NOT EXISTS lab5.bronze.checkpoints;
CREATE VOLUME IF NOT EXISTS lab5.bronze.customer_landing;
